Create doc/netbsd.txt, "make testall" fails there
This is the first error:

  cc -Wall -Wextra -Werror -O0 -c -g -DSQLITE_ENABLE_JSON1 sqlite3.c
  sqlite3.c: In function ‘sqlite3OsFetch’:
  sqlite3.c:19929:49: error: unused parameter ‘id’
[-Werror=unused-parameter]
   SQLITE_PRIVATE int sqlite3OsFetch(sqlite3_file *id, i64 iOff, int
iAmt, void **pp){

and then nine more "unused parameter" errors follow.

370c0530-b198-11e6-a999-6711e8bb1b6b