Makefile: Don't use -pedantic during compile
gcc 4.7.2 on Debian 7.11 doesn't like it, fails with "uuid.c:191:2:
error: integer constant is too large for ‘long’ type
[-Werror=long-long]". Adding LL suffix to EPOCH_DIFF (which I'm not a
fan of unless it's ambiguous) reduces the error to "uuid.c:191:31:
error: use of C99 long long integer constant [-Werror=long-long]". Seems
as -pedantic assumes C89, that won't work with for example long long.

bcbfcb50-3943-11e9-a2ad-4f45262dc9b5