Fix compile error with gcc-4.9.2, don't use -pedantic with USE_SQLITE
It's the old "long long" story all over again, some compilers complain
when compiling sqlite3 with -pedantic:

  cc -Wall -Wextra -Werror -O0 -c -g $(test -n "" && echo -n
  "-fprofile-arcs -ftest-coverage -DGCOV=1") $(test -n "" && echo -n
  "-DNDEBUG=1") -pedantic -DUSE_SQLITE suuid.c
  In file included from common.h:39:0,
                   from suuid.h:24,
                   from suuid.c:21:
  sqlite3.h:275:16: error: ISO C90 does not support ‘long long’
  [-Werror=long-long]
     typedef long long int sqlite_int64;
                  ^
  sqlite3.h:276:25: error: ISO C90 does not support ‘long long’
  [-Werror=long-long]
     typedef unsigned long long int sqlite_uint64;
                           ^
  cc1: all warnings being treated as errors
  Makefile:98: recipe for target 'suuid.o' failed
  make: *** [suuid.o] Error 1
  $

It's been like this since commit 13b3678b4b4a ("Invert the meaning of
USE_SQLITE, it's sane again", 2017-10-27). gcc-5.4.0 or gcc-7.2.0
don't complain.

Also move the comment about this to a better place.

18646a54-e780-11e7-91b7-db5caa6d21d3